/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JavaAssignment;

import javax.swing.JOptionPane;

/**
 *
 * @author homew
 */
public class AdminMain extends javax.swing.JFrame {

    /**
     * Creates new form RoomBooking
     */
    public AdminMain() {
        initComponents();
        setLocationRelativeTo(null);
    }

    AdminMain(String selectedid) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnaddcar = new javax.swing.JButton();
        jbtnviewcar = new javax.swing.JButton();
        jbtncustomerDetails = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbtnexit = new javax.swing.JButton();
        jbtnlogout = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbtnreport = new javax.swing.JButton();
        jbtnbookingConfirmation = new javax.swing.JButton();
        jbtnreceipt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtnaddcar.setText("ADD CAR ");
        jbtnaddcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaddcarActionPerformed(evt);
            }
        });

        jbtnviewcar.setText("MODIFY/DELETE CAR ");
        jbtnviewcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnviewcarActionPerformed(evt);
            }
        });

        jbtncustomerDetails.setText("CUSTOMERS DETAILS ");
        jbtncustomerDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncustomerDetailsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        jLabel1.setText("CAR RENTAL BOOKING SYSTEM");

        jbtnexit.setText("EXIT");
        jbtnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnexitActionPerformed(evt);
            }
        });

        jbtnlogout.setText("LOGOUT");
        jbtnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnlogoutActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JavaAssignment/b.jpg"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        jLabel4.setText("ADMIN DASHBOARD");

        jbtnreport.setText("REPORT");
        jbtnreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnreportActionPerformed(evt);
            }
        });

        jbtnbookingConfirmation.setText("CAR BOOKING CONFIRMATION ");
        jbtnbookingConfirmation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbookingConfirmationActionPerformed(evt);
            }
        });

        jbtnreceipt.setText("RECEIPT");
        jbtnreceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnreceiptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jbtnbookingConfirmation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jbtnaddcar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbtnviewcar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbtncustomerDetails, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnlogout)
                                    .addGap(18, 18, 18)
                                    .addComponent(jbtnexit))
                                .addComponent(jbtnreceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbtnreport, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel4)
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jbtnaddcar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jbtnviewcar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jbtncustomerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jbtnbookingConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jbtnreceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jbtnreport, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnexit)
                    .addComponent(jbtnlogout))
                .addGap(25, 25, 25))
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnlogoutActionPerformed
        JOptionPane.showMessageDialog(this, "Successfully Logout.");
        this.setVisible(false);
        AdminLoginForm Info = new AdminLoginForm();
        Info.setLocationRelativeTo(null);
        Info.setVisible(true);
    }//GEN-LAST:event_jbtnlogoutActionPerformed

    private void jbtnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtnexitActionPerformed

    private void jbtnaddcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaddcarActionPerformed
        this.setVisible(false);
        AdminAddCarForm Info = new AdminAddCarForm();
        Info.setVisible(true);
    }//GEN-LAST:event_jbtnaddcarActionPerformed

    private void jbtnviewcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnviewcarActionPerformed
        this.setVisible(false);
        AdminSearchCarDetailsList Info = new AdminSearchCarDetailsList();
        Info.setVisible(true);
    }//GEN-LAST:event_jbtnviewcarActionPerformed

    private void jbtnreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnreportActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AdminReportList Info = new AdminReportList();
        Info.setVisible(true);
    }//GEN-LAST:event_jbtnreportActionPerformed

    private void jbtnbookingConfirmationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbookingConfirmationActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AdminBookingDetailsList Info = new AdminBookingDetailsList();
        Info.setVisible(true);
    }//GEN-LAST:event_jbtnbookingConfirmationActionPerformed

    private void jbtncustomerDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncustomerDetailsActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AdminSearchCustomerDetailsList Info = new AdminSearchCustomerDetailsList();
        Info.setVisible(true);
    }//GEN-LAST:event_jbtncustomerDetailsActionPerformed

    private void jbtnreceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnreceiptActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AdminReceiptLists Info = new AdminReceiptLists();
        Info.setVisible(true);
    }//GEN-LAST:event_jbtnreceiptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbtnaddcar;
    private javax.swing.JButton jbtnbookingConfirmation;
    private javax.swing.JButton jbtncustomerDetails;
    private javax.swing.JButton jbtnexit;
    private javax.swing.JButton jbtnlogout;
    private javax.swing.JButton jbtnreceipt;
    private javax.swing.JButton jbtnreport;
    private javax.swing.JButton jbtnviewcar;
    // End of variables declaration//GEN-END:variables
}
