/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JavaAssignment;

import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author homew
 */
public class AdminReceiptLists extends javax.swing.JFrame {

    /**
     * Creates new form ViewBooking
     */
    public AdminReceiptLists() {
        initComponents();
        setLocationRelativeTo(null);
        
        //Allow Row selection instead of individual selection on the table list.
        bookinglisttable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        bookinglisttable.setFocusable(false);
        
        //Load all the data to the table list
        Booking.bookingdetails((DefaultTableModel) bookinglisttable.getModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbtnview = new javax.swing.JButton();
        jbtnclear = new javax.swing.JButton();
        jbtnback = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookinglisttable = new javax.swing.JTable();
        jbtnrefresh = new javax.swing.JButton();
        jbtnmodify = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        jLabel1.setText("View Receipt List");

        jtxtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtnameActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter Booking ID/Status :");

        jbtnview.setText("VIEW");
        jbtnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnviewActionPerformed(evt);
            }
        });

        jbtnclear.setText("CLEAR");
        jbtnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnclearActionPerformed(evt);
            }
        });

        jbtnback.setText("BACK");
        jbtnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbackActionPerformed(evt);
            }
        });

        bookinglisttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Booking ID ", "Username", "Car Plate Number", "Start Date ", "End Date ", "Price Per Day ", "Total Price ", "Card Number ", "CVV", "Status"
            }
        ));
        jScrollPane1.setViewportView(bookinglisttable);

        jbtnrefresh.setText("REFRESH");
        jbtnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnrefreshActionPerformed(evt);
            }
        });

        jbtnmodify.setText("GENERATE RECEIPT");
        jbtnmodify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmodifyActionPerformed(evt);
            }
        });

        jLabel3.setText("Additional Functions");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JavaAssignment/f.jpg"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel5.setText("Select one list in the table above to make additional function and select the function button below.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnback)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtname, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jbtnview)
                        .addGap(41, 41, 41)
                        .addComponent(jbtnclear)
                        .addGap(34, 34, 34)
                        .addComponent(jbtnrefresh)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addGap(298, 298, 298))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(463, 463, 463)
                        .addComponent(jbtnmodify))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1054, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jbtnback))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jbtnclear)
                    .addComponent(jbtnview)
                    .addComponent(jbtnrefresh))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnmodify)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtnameActionPerformed
        
    }//GEN-LAST:event_jtxtnameActionPerformed

    private void jbtnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnviewActionPerformed
        //Validation if none of the user is selected and prompt user the error.
        if (jtxtname.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please Enter a BookingID", "Message", JOptionPane.ERROR_MESSAGE);
        } else {
            //If user is selected then get user name or room ID text input with row filter. Index 0 and 6 from the booking details data.
            TableRowSorter rowSorter = new TableRowSorter((DefaultTableModel) bookinglisttable.getModel());
            rowSorter.setRowFilter(RowFilter.regexFilter(jtxtname.getText(), 0, 9));
            bookinglisttable.setRowSorter(rowSorter);
        }
    }//GEN-LAST:event_jbtnviewActionPerformed

    private void jbtnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbackActionPerformed
        this.setVisible(false);
        AdminMain Info = new AdminMain();
        Info.setVisible(true);
    }//GEN-LAST:event_jbtnbackActionPerformed

    private void jbtnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnclearActionPerformed
        jtxtname.setText(null);
    }//GEN-LAST:event_jbtnclearActionPerformed

    private void jbtnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnrefreshActionPerformed
        this.setVisible(false);
        AdminReceiptLists Info = new AdminReceiptLists();
        Info.setVisible(true);
    }//GEN-LAST:event_jbtnrefreshActionPerformed

    private void jbtnmodifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmodifyActionPerformed
        //Select row from the booking list table
        int row = bookinglisttable.getSelectedRow();
        //Open receipt form with the selectedid which is the booking id from row index 0.
        if (row != -1) {
            String selectedid = bookinglisttable.getValueAt(row, 0).toString();
            AdminReceiptForm mbf = new AdminReceiptForm(selectedid);
            mbf.setLocationRelativeTo(null);
            mbf.setVisible(true);
            dispose();
        } else {
            //If no record is selected then this error will be prompt to the user
            JOptionPane.showMessageDialog(this, "No record is selected", "Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtnmodifyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminReceiptLists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminReceiptLists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminReceiptLists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminReceiptLists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminReceiptLists().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bookinglisttable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnback;
    private javax.swing.JButton jbtnclear;
    private javax.swing.JButton jbtnmodify;
    private javax.swing.JButton jbtnrefresh;
    private javax.swing.JButton jbtnview;
    private javax.swing.JTextField jtxtname;
    // End of variables declaration//GEN-END:variables
}
