/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JavaAssignment;

import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author homew
 */
public class AdminReportList extends javax.swing.JFrame {

    /**
     * Creates new form ViewBooking
     */
    public AdminReportList() {
        initComponents();
        setLocationRelativeTo(null);

        //Allow Row selection instead of individual selection on the table list.
        bookinglisttable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        bookinglisttable.setFocusable(false);

        //Load all the data to the table list
        Booking.bookingdetails((DefaultTableModel) bookinglisttable.getModel());
        getSum();
        getMax();
        getMin();
        NoOfSales();
        getMaxCarValue();
        getMinCarValue();
        PendingSales();
        SucessfulSales();
        FailedSales();

    }

    public void getSum() {
        int sum = 0;
        for (int i = 0; i < bookinglisttable.getRowCount(); i++) {
            sum = sum + Integer.parseInt(bookinglisttable.getValueAt(i, 6).toString());
        }

        jtxtTotalSales.setText(Integer.toString(sum));
    }

    public void getMax() {
        int max2 = 0;

        for (int i = 0; i < bookinglisttable.getRowCount(); i++) {
            int val = Integer.parseInt(bookinglisttable.getValueAt(i, 6).toString());
            if (val > max2) {
                max2 = val;
            }
        }
        jtxtMaxSales.setText(Integer.toString(max2));
    }

    public void getMin() {
        int min = 0;
        for (int i = 0; i < bookinglisttable.getRowCount(); i++) {
            if (i == 0) {
                min = Integer.parseInt(bookinglisttable.getValueAt(i, 6).toString());
            } else {
                int val = Integer.parseInt(bookinglisttable.getValueAt(i, 6).toString());
                if (min > val) {
                    min = val;
                }
            }
        }
        jtxtMinSales.setText(Integer.toString(min));

    }

    public void NoOfSales() {
        int rows = bookinglisttable.getRowCount();
        jtxtNoOfSales.setText(Integer.toString(rows));
    }

    public void getMaxCarValue() {
        int max2 = 0;

        for (int i = 0; i < bookinglisttable.getRowCount(); i++) {
            int val = Integer.parseInt(bookinglisttable.getValueAt(i, 5).toString());
            if (val > max2) {
                max2 = val;
            }
        }
        HighestCarPrice1.setText(Integer.toString(max2));
    }

    public void getMinCarValue() {
        int min = 0;
        for (int i = 0; i < bookinglisttable.getRowCount(); i++) {
            if (i == 0) {
                min = Integer.parseInt(bookinglisttable.getValueAt(i, 6).toString());
            } else {
                int val = Integer.parseInt(bookinglisttable.getValueAt(i, 6).toString());
                if (min > val) {
                    min = val;
                }
            }
        }
        CheapestCar1.setText(Integer.toString(min));
    }

    public void PendingSales() {
        int amount = 0;
        for (int i = 0; i < bookinglisttable.getRowCount(); i++) {
            if (bookinglisttable.getValueAt(i, 9).equals("Pending")) {
                amount++;
            }
        }
        TotalPendingSales.setText("" + amount);
    }
    
    public void SucessfulSales() {
        int amount = 0;
        for (int i = 0; i < bookinglisttable.getRowCount(); i++) {
            if (bookinglisttable.getValueAt(i, 9).equals("Successfull")) {
                amount++;
            }
        }
        jtxtsuccess.setText("" + amount);
    }
    
    public void FailedSales() {
        int amount = 0;
        for (int i = 0; i < bookinglisttable.getRowCount(); i++) {
            if (bookinglisttable.getValueAt(i, 9).equals("Failed")) {
                amount++;
            }
        }
        jtxtfailed.setText("" + amount);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbtnview = new javax.swing.JButton();
        jbtnclear = new javax.swing.JButton();
        jbtnback = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookinglisttable = new javax.swing.JTable();
        jbtnrefresh = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtxtTotalSales = new javax.swing.JTextField();
        jtxtMaxSales = new javax.swing.JTextField();
        jtxtNoOfSales = new javax.swing.JTextField();
        jtxtMinSales = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TotalPendingSales = new javax.swing.JTextField();
        jtxtsuccess = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        HighestCarPrice1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        CheapestCar1 = new javax.swing.JTextField();
        jtxtfailed = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        jLabel1.setText("View Report List");

        jtxtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtnameActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter Booking ID/Status :");

        jbtnview.setText("VIEW");
        jbtnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnviewActionPerformed(evt);
            }
        });

        jbtnclear.setText("CLEAR");
        jbtnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnclearActionPerformed(evt);
            }
        });

        jbtnback.setText("BACK");
        jbtnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbackActionPerformed(evt);
            }
        });

        bookinglisttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Booking ID ", "Username", "Car Plate Number", "Start Date ", "End Date ", "Price Per Day ", "Total Price (RM) ", "Card Number ", "CVV", "Status"
            }
        ));
        jScrollPane1.setViewportView(bookinglisttable);

        jbtnrefresh.setText("REFRESH");
        jbtnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnrefreshActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JavaAssignment/f.jpg"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        jLabel6.setText("Overall Report");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Total Sales: ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Top Sales:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("No. Of Sales");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Least Sales:");

        jtxtTotalSales.setEditable(false);
        jtxtTotalSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalSalesActionPerformed(evt);
            }
        });

        jtxtMaxSales.setEditable(false);
        jtxtMaxSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMaxSalesActionPerformed(evt);
            }
        });

        jtxtNoOfSales.setEditable(false);
        jtxtNoOfSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNoOfSalesActionPerformed(evt);
            }
        });

        jtxtMinSales.setEditable(false);
        jtxtMinSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMinSalesActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Max Car Value:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Min Car Value:");

        TotalPendingSales.setEditable(false);
        TotalPendingSales.setFont(new java.awt.Font("Segoe UI", 0, 80)); // NOI18N
        TotalPendingSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalPendingSalesActionPerformed(evt);
            }
        });

        jtxtsuccess.setEditable(false);
        jtxtsuccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtsuccessActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setText("Pending Sales");

        HighestCarPrice1.setEditable(false);
        HighestCarPrice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HighestCarPrice1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Total Successful Status:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Total Failed Status:");

        CheapestCar1.setEditable(false);
        CheapestCar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheapestCar1ActionPerformed(evt);
            }
        });

        jtxtfailed.setEditable(false);
        jtxtfailed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfailedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnback)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtname, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jbtnview)
                        .addGap(41, 41, 41)
                        .addComponent(jbtnclear)
                        .addGap(34, 34, 34)
                        .addComponent(jbtnrefresh)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxtTotalSales, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxtMaxSales, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxtMinSales, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxtNoOfSales, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtxtsuccess, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(HighestCarPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(CheapestCar1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(jtxtfailed, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TotalPendingSales, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(4, 4, 4)))
                                .addGap(108, 108, 108)))
                        .addContainerGap())))
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1052, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jbtnback))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jbtnclear)
                    .addComponent(jbtnview)
                    .addComponent(jbtnrefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtxtTotalSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(HighestCarPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jtxtMaxSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(CheapestCar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtxtMinSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jtxtNoOfSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(jtxtsuccess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jtxtfailed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TotalPendingSales, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addGap(45, 45, 45))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtnameActionPerformed

    }//GEN-LAST:event_jtxtnameActionPerformed

    private void jbtnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnviewActionPerformed
        //Validation if none of the user is selected and prompt user the error.
        if (jtxtname.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Enter a BookingID/Status", "Message", JOptionPane.ERROR_MESSAGE);
        } else {
            //If user is selected then get user name or room ID text input with row filter. Index 0 and 6 from the booking details data.
            TableRowSorter rowSorter = new TableRowSorter((DefaultTableModel) bookinglisttable.getModel());
            rowSorter.setRowFilter(RowFilter.regexFilter(jtxtname.getText(), 0, 9));
            bookinglisttable.setRowSorter(rowSorter);
        }
    }//GEN-LAST:event_jbtnviewActionPerformed

    private void jbtnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbackActionPerformed
        this.setVisible(false);
        AdminMain Info = new AdminMain();
        Info.setVisible(true);
    }//GEN-LAST:event_jbtnbackActionPerformed

    private void jbtnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnclearActionPerformed
        jtxtname.setText(null);
    }//GEN-LAST:event_jbtnclearActionPerformed

    private void jbtnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnrefreshActionPerformed
        this.setVisible(false);
        AdminReportList Info = new AdminReportList();
        Info.setVisible(true);
    }//GEN-LAST:event_jbtnrefreshActionPerformed

    private void jtxtTotalSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalSalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalSalesActionPerformed

    private void jtxtMaxSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMaxSalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtMaxSalesActionPerformed

    private void jtxtNoOfSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNoOfSalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNoOfSalesActionPerformed

    private void jtxtMinSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMinSalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtMinSalesActionPerformed

    private void TotalPendingSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalPendingSalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalPendingSalesActionPerformed

    private void jtxtsuccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtsuccessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtsuccessActionPerformed

    private void HighestCarPrice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HighestCarPrice1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HighestCarPrice1ActionPerformed

    private void CheapestCar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheapestCar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheapestCar1ActionPerformed

    private void jtxtfailedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfailedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtfailedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminReportList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminReportList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminReportList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminReportList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminReportList().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CheapestCar1;
    private javax.swing.JTextField HighestCarPrice1;
    private javax.swing.JTextField TotalPendingSales;
    private javax.swing.JTable bookinglisttable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnback;
    private javax.swing.JButton jbtnclear;
    private javax.swing.JButton jbtnrefresh;
    private javax.swing.JButton jbtnview;
    private javax.swing.JTextField jtxtMaxSales;
    private javax.swing.JTextField jtxtMinSales;
    private javax.swing.JTextField jtxtNoOfSales;
    private javax.swing.JTextField jtxtTotalSales;
    private javax.swing.JTextField jtxtfailed;
    private javax.swing.JTextField jtxtname;
    private javax.swing.JTextField jtxtsuccess;
    // End of variables declaration//GEN-END:variables
}
