/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JavaAssignment;

import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Celine Ooi Zhi Ni
 */
public class CustomerAddBookingList extends javax.swing.JFrame {

    /**
     * Creates new form CustomerAddBookingList
     * @param selectedid
     */
    public void CustomerAddBookingList(String selectedid) {
        initComponents();
        setLocationRelativeTo(null);
        jtxtname.setText(selectedid);
        
        //Allow Row selection instead of individual selection on the table list.
        AvailableCarLists.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        AvailableCarLists.setFocusable(false);
        
        //Load all the data to the table list
        Booking.Loadcardetailstable((DefaultTableModel) AvailableCarLists.getModel());
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtCarModel = new javax.swing.JTextField();
        jbtnback = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AvailableCarLists = new javax.swing.JTable();
        jbtnBook = new javax.swing.JButton();
        jtxtname = new javax.swing.JLabel();
        jtxtname1 = new javax.swing.JLabel();
        jbtnview = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JavaAssignment/f.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        jLabel1.setText("Car List");

        jLabel2.setText("Enter Car Model :");

        jtxtCarModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCarModelActionPerformed(evt);
            }
        });

        jbtnback.setText("BACK");
        jbtnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbackActionPerformed(evt);
            }
        });

        AvailableCarLists.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Car Brand ", "Car Model ", "Car Type ", "Car Plate No ", "Seats", "Car Colour", "Fuel Type ", "Price Per day "
            }
        ));
        jScrollPane1.setViewportView(AvailableCarLists);

        jbtnBook.setText("BOOK");
        jbtnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBookActionPerformed(evt);
            }
        });

        jtxtname.setText("jLabel3");

        jtxtname1.setText("Welcome :");

        jbtnview.setText("View");
        jbtnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnviewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtCarModel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jbtnview)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnBook))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(23, 23, 23)
                        .addComponent(jtxtname1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtname, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnback)))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1037, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jbtnback)
                    .addComponent(jtxtname)
                    .addComponent(jtxtname1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtCarModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnBook)
                    .addComponent(jbtnview))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtCarModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCarModelActionPerformed

    }//GEN-LAST:event_jtxtCarModelActionPerformed

    private void jbtnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbackActionPerformed
        String username = jtxtname.getText();
        
        this.setVisible(false);
        CustomerMain Info =new CustomerMain();
        Info.setLocationRelativeTo(null);
        Info.CustomerMain(username);
        Info.setVisible(true);
    }//GEN-LAST:event_jbtnbackActionPerformed

    private void jbtnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBookActionPerformed
        // TODO add your handling code here:
        String username = jtxtname.getText();
        
        //Select row from the booking table
        int row = AvailableCarLists.getSelectedRow();
        //Open Modify booking form with the selectedid which is the username from row index 0.
        if (row != -1) {
            String selectedid = AvailableCarLists.getValueAt(row, 0).toString();
            CustomerBookingDetailsForm info = new CustomerBookingDetailsForm();
            info.setLocationRelativeTo(null);
            info.CustomerBookingDetailsForm(username, selectedid);
            info.setVisible(true);
            dispose();
        } else {
            //If no record is selected then this error will be prompt to the user
            JOptionPane.showMessageDialog(this, "No record is selected", "Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtnBookActionPerformed

    private void jbtnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnviewActionPerformed
        // TODO add your handling code here:
                //Validation if none of the user is selected and prompt user the error.
        if (jtxtCarModel.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please Enter a Car Brand", "Message", JOptionPane.ERROR_MESSAGE);
        } else {
            //If user is selected then get user name or room ID text input with row filter. Index 0 and 6 from the booking details data.
            TableRowSorter rowSorter = new TableRowSorter((DefaultTableModel) AvailableCarLists.getModel());
            rowSorter.setRowFilter(RowFilter.regexFilter(jtxtCarModel.getText(), 0, 6));
            AvailableCarLists.setRowSorter(rowSorter);
        }
    }//GEN-LAST:event_jbtnviewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerAddBookingList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerAddBookingList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerAddBookingList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerAddBookingList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerAddBookingList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AvailableCarLists;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnBook;
    private javax.swing.JButton jbtnback;
    private javax.swing.JButton jbtnview;
    private javax.swing.JTextField jtxtCarModel;
    private javax.swing.JLabel jtxtname;
    private javax.swing.JLabel jtxtname1;
    // End of variables declaration//GEN-END:variables
}
