/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JavaAssignment;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Celine Ooi Zhi Ni
 */
public class CustomerBookingDetailsForm extends javax.swing.JFrame {
   /**
     * Creates new form CustomerBookingDetailsForm
     * @param selectedid 
     * @param username
     */
    public void CustomerBookingDetailsForm(String selectedid, String username) {
        initComponents();
        setLocationRelativeTo(null);
        jtxtname.setText(selectedid);
        
        //Load and store all the car data into an arraylist
        ArrayList<String> cardata = LoadData.cardetailsdata();
        
        //Create an arraylist to append the new selected car data
        ArrayList<String> data = new ArrayList<String>();

        //Load out all the data of the car which has the same id with the String selectedid
        int index = 0, count = 0;
        while (index < cardata.size()) {
            if (cardata.get(index).equals(username)) {
                count = index;
                break;
            }
            index++;
        }
        //One car booking data contains 8 different data so repeat steps 8 times.
        for (int i = 0; i != 8; i++) {
            data.add(cardata.get(count));
            count++;
        }
        
        
        jtxtCarBrand.setText(data.get(0));
        jtxtCarModel.setText(data.get(1));
        jtxtCarType.setText(data.get(2));
        jtxtCarPlateNo.setText(data.get(3));
        jtxtSeats.setText(data.get(4));
        jtxtCarColour.setText(data.get(5));
        jtxtFeulType.setText(data.get(6));
        jtxtPricePerDay.setText(data.get(7));
        
        //Set date format to yyyy/mm/dd to maintain an correct order throughout entire process
        jtxtstartdate.setDateFormatString("yyyy/MM/dd");
        jtxtenddate.setDateFormatString("yyyy/MM/dd");
        
        //Set date range for users
        Calendar cal = Calendar.getInstance();
        cal.add(Calendar.DATE, 3);
        //Create date variable to get time.
        Date mindate = cal.getTime();
        cal.add(Calendar.YEAR, 1);
        Date maxdate = cal.getTime();
        //Set minimum and maximum date range
        jtxtstartdate.setDate(mindate);
        jtxtstartdate.setSelectableDateRange(mindate, maxdate);
        jtxtenddate.setDate(mindate);
        //jtxtenddate.setSelectableDateRange(mindate, maxdate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtCarBrand = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtxtCarModel = new javax.swing.JTextField();
        jtxtCarType = new javax.swing.JTextField();
        jtxtSeats = new javax.swing.JTextField();
        jtxtCarColour = new javax.swing.JTextField();
        jtxtFeulType = new javax.swing.JTextField();
        jtxtPricePerDay = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtxtstartdate = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jspinday = new com.toedter.components.JSpinField();
        jLabel10 = new javax.swing.JLabel();
        jtxtenddate = new com.toedter.calendar.JDateChooser();
        jbtnconfirm = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jtxtprice = new javax.swing.JTextField();
        jbtnclear = new javax.swing.JButton();
        jbtnback = new javax.swing.JButton();
        jbtnConfirm = new javax.swing.JButton();
        jtxtAvailability = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jtxtCardNo = new javax.swing.JTextField();
        jtxtCVV = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtxtCarPlateNo = new javax.swing.JTextField();
        jtxtname = new javax.swing.JLabel();
        jtxtname1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JavaAssignment/b.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        jLabel1.setText("Add Car Rental Booking");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Car Brand : ");

        jtxtCarBrand.setEditable(false);
        jtxtCarBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCarBrandActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Car Model : ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Car Type : ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Available Seats : ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Car Colour : ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("End Date : ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Car Price/day : ");

        jtxtCarModel.setEditable(false);
        jtxtCarModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCarModelActionPerformed(evt);
            }
        });

        jtxtCarType.setEditable(false);
        jtxtCarType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCarTypeActionPerformed(evt);
            }
        });

        jtxtSeats.setEditable(false);
        jtxtSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSeatsActionPerformed(evt);
            }
        });

        jtxtCarColour.setEditable(false);
        jtxtCarColour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCarColourActionPerformed(evt);
            }
        });

        jtxtFeulType.setEditable(false);
        jtxtFeulType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFeulTypeActionPerformed(evt);
            }
        });

        jtxtPricePerDay.setEditable(false);
        jtxtPricePerDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPricePerDayActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Start Date : ");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("No of Days :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Fuel Type :");

        jbtnconfirm.setText("CHECK");
        jbtnconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnconfirmActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Total Price (RM) : ");

        jtxtprice.setEditable(false);

        jbtnclear.setText("CLEAR");
        jbtnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnclearActionPerformed(evt);
            }
        });

        jbtnback.setText("BACK");
        jbtnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbackActionPerformed(evt);
            }
        });

        jbtnConfirm.setText("CONFIRM BOOKING ");
        jbtnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConfirmActionPerformed(evt);
            }
        });

        jtxtAvailability.setEditable(false);
        jtxtAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAvailabilityActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        jLabel14.setText("Payment Details");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Card Number : ");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("CVV : ");

        jtxtCardNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCardNoActionPerformed(evt);
            }
        });

        jtxtCVV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCVVActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Car Plate : ");

        jtxtCarPlateNo.setEditable(false);
        jtxtCarPlateNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCarPlateNoActionPerformed(evt);
            }
        });

        jtxtname.setText("jLabel18");

        jtxtname1.setText("Welcome :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtxtCVV))
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtxtCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtxtenddate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtxtstartdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtxtSeats, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtCarColour, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtFeulType, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtPricePerDay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                    .addComponent(jspinday, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtxtprice, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtxtAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbtnconfirm))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtxtCarBrand, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtCarModel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtCarType, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtCarPlateNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(44, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtname1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtname, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jbtnclear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnConfirm)
                        .addGap(55, 55, 55)
                        .addComponent(jbtnback, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtname1)
                        .addComponent(jtxtname)))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtCarBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtCarModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtCarType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jtxtCarPlateNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtCarColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtFeulType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtxtPricePerDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jtxtstartdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jspinday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jtxtenddate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jbtnconfirm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jtxtAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jtxtCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jtxtCVV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnclear)
                    .addComponent(jbtnback, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnConfirm))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtCarBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCarBrandActionPerformed

    }//GEN-LAST:event_jtxtCarBrandActionPerformed

    private void jtxtCarModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCarModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCarModelActionPerformed

    private void jtxtCarTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCarTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCarTypeActionPerformed

    private void jtxtSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSeatsActionPerformed

    private void jtxtCarColourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCarColourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCarColourActionPerformed

    private void jtxtFeulTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFeulTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFeulTypeActionPerformed

    private void jtxtPricePerDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPricePerDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPricePerDayActionPerformed

    private void jbtnconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnconfirmActionPerformed

        int priceperday = jtxtPricePerDay.getColumns();
        
            try {
                //Set date format
                SimpleDateFormat DateFormat = new SimpleDateFormat("yyyy/MM/dd");

                //Get start date input and convert into string.
                String startdate = DateFormat.format(jtxtstartdate.getDate());

                //Get end date input and convert into string.
                String enddate = DateFormat.format(jtxtenddate.getDate());
                
                //JOptionPane.showMessageDialog(this, "Print" + enddate , "Message", JOptionPane.ERROR_MESSAGE);

                //Arraylist will store and list out all the booked room id received from the function below.
                ArrayList<String> bookedroomid = Booking.bookedcar(startdate, enddate);

                //Delete the booked room id contained in the arraylist from the RoomID combo box
                int index = 0;
                while (index == bookedroomid.size()) {
                    jtxtAvailability.setText("Available");
                    index++;
                }

            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(this, "Please insert a date.", "Message", JOptionPane.ERROR_MESSAGE);
            }

        //Calculate the price 
        if (jtxtAvailability.getText().equals("Available")) {
            int price = ((Integer) jspinday.getValue() * Integer.parseInt(jtxtPricePerDay.getText()));
            jtxtprice.setText(String.valueOf(price));
        } else {
            JOptionPane.showMessageDialog(this, "Not Available.", "Message", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jbtnconfirmActionPerformed

    private void jbtnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnclearActionPerformed
        jtxtCarBrand.setText(null);
        jtxtCarModel.setText(null);
        jtxtCarType.setText(null);
        jtxtCarPlateNo.setText(null);
        jtxtSeats.setText(null);
        jtxtCarColour.setText(null);
        jtxtFeulType.setText(null);
        jtxtPricePerDay.setText(null);
    }//GEN-LAST:event_jbtnclearActionPerformed

    private void jbtnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbackActionPerformed
        String username = jtxtname.getText();
        
        this.setVisible(false);
        CustomerMain Info =new CustomerMain();
        Info.setLocationRelativeTo(null);
        Info.CustomerMain(username);
        Info.setVisible(true);
    }//GEN-LAST:event_jbtnbackActionPerformed

    private void jtxtAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAvailabilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAvailabilityActionPerformed

    private void jtxtCardNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCardNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCardNoActionPerformed

    private void jtxtCVVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCVVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCVVActionPerformed

    private void jtxtCarPlateNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCarPlateNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCarPlateNoActionPerformed

    private void jbtnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConfirmActionPerformed
        // TODO add your handling code here:
            //add booking from all input
                
            //Set date format
                SimpleDateFormat DateFormat = new SimpleDateFormat("yyyy/MM/dd");

                //Get start date input and convert into string.
                String startdate = DateFormat.format(jtxtstartdate.getDate());

                //Get end date input and convert into string.
                String enddate = DateFormat.format(jtxtenddate.getDate());
                
                SimpleDateFormat DateFormat1 = new SimpleDateFormat("yyyyMMdd");

                //Get start date input and convert into string.
                String startdate1 = DateFormat1.format(jtxtstartdate.getDate());
                
                String bookingid = "B"+jtxtCarPlateNo.getText()+jtxtname.getText()+startdate1;
                
            if (bookingid.isEmpty() || jtxtname.getText().isEmpty() || jtxtCarPlateNo.getText().isEmpty() || startdate.isEmpty() || enddate.isEmpty() || jtxtPricePerDay.getText().isEmpty() || jtxtprice.getText().isEmpty() || jtxtCardNo.getText().isEmpty() || jtxtCVV.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Please fill in the blank.");
            }
            else {                                
                Booking.addbookingdetails(bookingid, jtxtname.getText(), jtxtCarPlateNo.getText(), startdate, enddate, jtxtPricePerDay.getText(), jtxtprice.getText(), jtxtCardNo.getText(), jtxtCVV.getText(), "Pending");

                //Once modification is successful then display Successfully Modified and prompt the Search Booking List Form to the user.
                JOptionPane.showMessageDialog(this, "Successfully Added.");
                String username = jtxtname.getText();
                CustomerMain brf = new CustomerMain();
                brf.CustomerMain(username);
                brf.setLocationRelativeTo(null);
                brf.setVisible(true);
                dispose();
            }

    }//GEN-LAST:event_jbtnConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerBookingDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerBookingDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerBookingDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerBookingDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerBookingDetailsForm("1").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbtnConfirm;
    private javax.swing.JButton jbtnback;
    private javax.swing.JButton jbtnclear;
    private javax.swing.JButton jbtnconfirm;
    private com.toedter.components.JSpinField jspinday;
    private javax.swing.JTextField jtxtAvailability;
    private javax.swing.JTextField jtxtCVV;
    private javax.swing.JTextField jtxtCarBrand;
    private javax.swing.JTextField jtxtCarColour;
    private javax.swing.JTextField jtxtCarModel;
    private javax.swing.JTextField jtxtCarPlateNo;
    private javax.swing.JTextField jtxtCarType;
    private javax.swing.JTextField jtxtCardNo;
    private javax.swing.JTextField jtxtFeulType;
    private javax.swing.JTextField jtxtPricePerDay;
    private javax.swing.JTextField jtxtSeats;
    private com.toedter.calendar.JDateChooser jtxtenddate;
    private javax.swing.JLabel jtxtname;
    private javax.swing.JLabel jtxtname1;
    private javax.swing.JTextField jtxtprice;
    private com.toedter.calendar.JDateChooser jtxtstartdate;
    // End of variables declaration//GEN-END:variables
}
